import Head from 'next/head'
import {useCallback, useState} from 'react'
import styles from '../styles/Home.module.css'

import { initGameStateWithBombCounts } from './services/data.js'

export default function Home() {

  const [gameState, setGameState] = useState(initGameStateWithBombCounts)

  const handleClickCell = useCallback((clickedCell) => {
    if (clickedCell.bomb === true) {
      return alert('You died')
    }

    const newGameState = gameState.map((row) => {
      return row.reduce((acc, cell) => {
        if (clickedCell.y === cell.y && clickedCell.x === cell.x) {
          acc.push({
            ...cell,
            revealed: true,
          })
        } else {
          acc.push(cell)
        }

        return acc;
      }, [])
    });

    setGameState(newGameState)
  })

  const renderedRows = gameState.map((row, rowIdx) => {
    const renderedCells = row.map((cell, cellIdx) => {
      const key = `[${cell.x}-${cell.y}]`;

      const renderedCellContents = (() => {
        if (cell.bomb === true) {
          return '(B)'
        }

        if (cell.revealed === true) {
          return `(${cell.bombSurroundCount})`
        }

        return '(-)'
      })()

      return (
        <div key={key} onClick={() => handleClickCell(cell)}>
          {renderedCellContents}
        </div>
      )
    })

    return (
      <div key={rowIdx} style={{display: 'flex', alignItems: 'center'}}>
        {renderedCells}
      </div>
    )
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {renderedRows}
      </main>
    </div>
  )
}
